name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "./ghostapp/*"
      - "./.github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        env:
          DOCKER_REPO: babug011/ghostapp
        run: |
          cd ./ghostapp/
          docker build -t $DOCKER_REPO:latest .
          docker push $DOCKER_REPO:latest

      - name: Store Docker image name as environment variable
        run: echo "DOCKER_IMAGE_NAME=ghostapp" >> $GITHUB_ENV
