name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          DOCKER_REPO: babug011/ghostapp
        run: |
          cd /ghostapp/
          docker build -t $DOCKER_REPO:latest .
          docker push $DOCKER_REPO:latest
